package cmd

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/0xkhdr/specd/internal/cli"
	"github.com/0xkhdr/specd/internal/core"
)

const (
	bootMarkerBegin = "<!-- SPECD BOOT: BEGIN v1 (regenerated by `specd boot` — do not edit) -->"
	bootMarkerEnd   = "<!-- SPECD BOOT: END v1 -->"
)

// RunBoot analyzes the repository with deterministic, AI-free detectors and
// populates .specd/ with the detected context: boot.json (machine-readable),
// a managed section in steering/tech.md, and config.json's defaultVerify.
func RunBoot(args cli.Args) int {
	root, err := core.RequireSpecdRoot()
	if err != nil {
		return specdExit(err)
	}
	force := args.Bool("force")
	dryRun := args.Bool("dry-run")
	jsonOut := args.Bool("json")

	res := core.AnalyzeBoot(root)
	res.GeneratedAt = time.Now().UTC().Format(time.RFC3339)

	outDir := args.Str("output-dir")
	if outDir == "" {
		outDir = core.SpecdDir(root)
	}
	bootPath := filepath.Join(outDir, "boot.json")
	techPath := filepath.Join(core.SteeringDir(root), "tech.md")

	relTo := func(p string) string { return strings.TrimPrefix(p, root+"/") }
	var actions []string

	if len(res.Stacks) == 0 {
		if jsonOut {
			emitBootJSON(res, []string{"no known tech stack detected"}, dryRun)
			return core.ExitOK
		}
		core.Warn("specd boot: no known tech stack detected — nothing to populate.")
		return core.ExitOK
	}

	// boot.json — fully owned by boot; regenerate only on --force once it exists.
	bootJSON, _ := json.MarshalIndent(res, "", "  ")
	switch {
	case dryRun:
		actions = append(actions, "would write "+relTo(bootPath))
	case core.FileExists(bootPath) && !force:
		actions = append(actions, "skip "+relTo(bootPath)+" (exists — use --force to regenerate)")
	default:
		if err := core.AtomicWrite(bootPath, string(bootJSON)+"\n"); err != nil {
			core.Error(fmt.Sprintf("write %s: %v", bootPath, err))
			return core.ExitGate
		}
		actions = append(actions, "write "+relTo(bootPath))
	}

	// tech.md — replace the managed section, preserve the rest (idempotent).
	if dryRun {
		actions = append(actions, "would merge "+relTo(techPath)+" (boot section)")
	} else {
		if err := core.MergeSection(techPath, bootMarkerBegin, bootMarkerEnd, bootTechBody(res)); err != nil {
			core.Error(fmt.Sprintf("merge %s: %v", techPath, err))
			return core.ExitGate
		}
		actions = append(actions, "merge "+relTo(techPath)+" (boot section)")
	}

	// config.json defaultVerify — non-destructive: only overwrite a hand-set
	// value with --force; otherwise update only the untouched template default.
	if res.Verify != "" {
		cfg := core.LoadConfig(root)
		switch {
		case cfg.DefaultVerify == res.Verify:
			// already correct, nothing to do
		case cfg.DefaultVerify == core.DefaultConfig.DefaultVerify || force:
			cfg.DefaultVerify = res.Verify
			if !dryRun {
				b, _ := json.MarshalIndent(cfg, "", "  ")
				if err := core.AtomicWrite(core.ConfigPath(root), string(b)+"\n"); err != nil {
					core.Error(fmt.Sprintf("write %s: %v", core.ConfigPath(root), err))
					return core.ExitGate
				}
			}
			actions = append(actions, fmt.Sprintf("set config.defaultVerify=%q", res.Verify))
		default:
			actions = append(actions, fmt.Sprintf("keep config.defaultVerify=%q (boot suggests %q — use --force)", cfg.DefaultVerify, res.Verify))
		}
	}

	if jsonOut {
		emitBootJSON(res, actions, dryRun)
		return core.ExitOK
	}

	core.Header("specd boot")
	fmt.Printf("project:  %s\n", res.ProjectName)
	fmt.Printf("stacks:   %s\n", strings.Join(res.Stacks, ", "))
	for _, s := range res.Stacks {
		if fw := res.Frameworks[s]; len(fw) > 0 {
			fmt.Printf("  %-8s %s\n", s+":", strings.Join(fw, ", "))
		}
	}
	if res.Verify != "" {
		fmt.Printf("verify:   %s  (%s)\n", res.Verify, res.VerifyFrom)
	}
	fmt.Printf("layout:   %s\n", res.Layout)
	if len(res.Build) > 0 {
		fmt.Printf("build:    %s\n", strings.Join(res.Build, ", "))
	}
	if len(res.CI) > 0 {
		fmt.Printf("ci:       %s\n", strings.Join(res.CI, ", "))
	}
	for _, c := range res.Conflicts {
		core.Warn(c)
	}
	fmt.Println()
	verb := "Applied"
	if dryRun {
		verb = "Planned (dry-run, nothing written)"
	}
	fmt.Println(verb + ":")
	for _, a := range actions {
		fmt.Println("  • " + a)
	}
	return core.ExitOK
}

func emitBootJSON(res core.BootResult, actions []string, dryRun bool) {
	if actions == nil {
		actions = []string{}
	}
	out := map[string]interface{}{
		"detection": res,
		"actions":   actions,
		"dryRun":    dryRun,
	}
	_ = core.PrintJSON(out)
}

func bootTechBody(res core.BootResult) string {
	var b strings.Builder
	b.WriteString("## Detected stack (specd boot)\n\n")
	b.WriteString("> Auto-generated by `specd boot` from deterministic file analysis — zero AI inference.\n")
	b.WriteString("> Re-run `specd boot --force` to refresh. Edits inside this block are overwritten.\n\n")
	b.WriteString(fmt.Sprintf("- **Project**: %s\n", res.ProjectName))
	b.WriteString(fmt.Sprintf("- **Stacks**: %s\n", strings.Join(res.Stacks, ", ")))
	for _, s := range res.Stacks {
		if fw := res.Frameworks[s]; len(fw) > 0 {
			b.WriteString(fmt.Sprintf("  - %s: %s\n", s, strings.Join(fw, ", ")))
		}
	}
	b.WriteString(fmt.Sprintf("- **Layout**: %s\n", res.Layout))
	if len(res.Build) > 0 {
		b.WriteString(fmt.Sprintf("- **Build**: %s\n", strings.Join(res.Build, ", ")))
	}
	if len(res.CI) > 0 {
		b.WriteString(fmt.Sprintf("- **CI**: %s\n", strings.Join(res.CI, ", ")))
	}
	b.WriteString("\n### Verify commands\n\n")
	if res.Verify != "" {
		b.WriteString(fmt.Sprintf("- `%s`  (inferred from %s)\n", res.Verify, res.VerifyFrom))
	}
	for _, alt := range res.VerifyAlts {
		b.WriteString(fmt.Sprintf("- alt: `%s`\n", alt))
	}
	b.WriteString("\n### Evidence\n\n")
	b.WriteString(fmt.Sprintf("Sources: %s\n", strings.Join(res.Sources, ", ")))
	return strings.TrimRight(b.String(), "\n")
}
