package core

type FlagMeta struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

type ExitCodeMeta struct {
	Code    int    `json:"code"`
	Meaning string `json:"meaning"`
}

type CommandMeta struct {
	Command         string         `json:"command"`
	Category        string         `json:"category"`
	Description     string         `json:"description"`
	Usage           string         `json:"usage"`
	Synopsis        string         `json:"synopsis"`
	LongDescription string         `json:"longDescription"`
	Flags           []FlagMeta     `json:"flags"`
	ExitCodes       []ExitCodeMeta `json:"exitCodes"`
	Examples        []string       `json:"examples"`
}

var Commands = []CommandMeta{
	{
		Command: "init", Category: "lifecycle",
		Description: "Scaffold project assets and configure coding agents",
		Usage:       "specd init [--agent <auto|all|none|codex|claude-code|cursor|gemini|vscode>] [--scope project|global] [--yes] [--non-interactive] [--verbose] [--dry-run] [--repair|--refresh|--force]", Synopsis: "specd init [--agent <name>] [--yes] [--dry-run]",
		LongDescription: "Scaffolds .specd/ and AGENTS.md, passively detects supported coding-agent hosts, optionally installs project-scoped MCP registration, verifies the in-process MCP server, and returns one next action. Non-interactive auto-detection never mutates host configuration unless --yes is supplied. Global scope requires explicit consent.",
		Flags:           []FlagMeta{{Name: "agent", Type: "string", Description: "Coding-agent selection: auto, all, none, codex, claude-code, cursor, gemini, or vscode"}, {Name: "scope", Type: "string", Description: "Integration scope (default project)"}, {Name: "yes", Type: "boolean", Description: "Accept non-destructive project-scoped integration changes"}, {Name: "non-interactive", Type: "boolean", Description: "Disable prompts"}, {Name: "verbose", Type: "boolean", Description: "Include detailed path results"}, {Name: "json", Type: "boolean", Description: "Output one versioned InitResult document"}, {Name: "dry-run", Type: "boolean", Description: "Preview exact actions without writing"}, {Name: "repair", Type: "boolean", Description: "Restore missing managed assets only"}, {Name: "refresh", Type: "boolean", Description: "Refresh frozen managed assets and AGENTS.md markers"}, {Name: "force", Type: "boolean", Description: "Destructively overwrite all scaffold files and AGENTS.md"}, {Name: "list-packs", Type: "boolean", Description: "List the embedded spec packs and exit"}, {Name: "pack", Type: "string", Description: "Apply a spec pack by built-in name or http(s) URL"}, {Name: "sha256", Type: "string", Description: "Pinned SHA256 digest required for a remote --pack URL"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Initialization or pack operation failed"}, {2, "Usage error"}},
		Examples:        []string{"specd init --agent auto --yes", "specd init --agent none --non-interactive", "specd init --agent all --dry-run --json", "specd init --repair"},
	},
	{
		Command: "doctor", Category: "inspection",
		Description: "Diagnose scaffold, MCP, and coding-agent registration",
		Usage:       "specd doctor [--agent <name|all>] [--fix] [--json]", Synopsis: "specd doctor [--agent <name|all>] [--fix] [--json]",
		LongDescription: "Checks the current project binary, required scaffold assets, in-process MCP handshake and baseline tools, detected coding-agent hosts, and project registration state. --fix repairs only safe project-scoped state and refuses conflicting or unowned registrations.",
		Flags:           []FlagMeta{{Name: "agent", Type: "string", Description: "Inspect one host or all detected hosts"}, {Name: "fix", Type: "boolean", Description: "Repair safe project-scoped scaffold and registration state"}, {Name: "json", Type: "boolean", Description: "Output one deterministic JSON document"}},
		ExitCodes:       []ExitCodeMeta{{0, "All requested checks pass"}, {1, "One or more health checks failed"}, {2, "Usage error"}},
		Examples:        []string{"specd doctor", "specd doctor --agent codex --json", "specd doctor --fix"},
	},
	{
		Command: "new", Category: "lifecycle",
		Description: "Create a spec with six artifacts",
		Usage:       "specd new <slug> [--title \"...\"]", Synopsis: "specd new <slug> [--title \"...\"]",
		LongDescription: "Creates a new spec directory under .specd/specs/<slug>/ with six artifact stubs.",
		Flags:           []FlagMeta{{Name: "title", Type: "string", Description: "The title of the spec"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, ".specd/ not found or spec already exists"}},
		Examples:        []string{"specd new my-feature", "specd new my-feature --title \"My Feature\""},
	},
	{
		Command: "approve", Category: "lifecycle",
		Description: "Clear approval gate / advance phase",
		Usage:       "specd approve <slug> [--json]", Synopsis: "specd approve <slug> [--json]",
		LongDescription: "Clears an awaiting-approval gate or advances the planning phase of the specified spec.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean", Description: "Output in JSON format"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Gate validation failed"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd approve my-feature", "specd approve my-feature --json"},
	},
	{
		Command: "decision", Category: "lifecycle",
		Description: "Record an architectural decision (ADR)",
		Usage:       "specd decision <slug> \"<text>\" [--supersedes <id>]", Synopsis: "specd decision <slug> \"<text>\" [--supersedes <id>]",
		LongDescription: "Appends an architectural decision record (ADR) to decisions.md.",
		Flags:           []FlagMeta{{Name: "supersedes", Type: "string", Description: "ID of the decision being superseded"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd decision my-feature \"Use SQLite instead of PostgreSQL\""},
	},
	{
		Command: "midreq", Category: "lifecycle",
		Description: "Log feedback mid-requirement",
		Usage:       "specd midreq <slug> \"<input>\" --impact <low|medium|high|critical>", Synopsis: "specd midreq <slug> \"<input>\" --impact <low|medium|high|critical>",
		LongDescription: "Logs user feedback or mid-requirement changes and triggers appropriate gates.",
		Flags:           []FlagMeta{{Name: "impact", Type: "string", Description: "Impact level (low/medium/high/critical)"}, {Name: "interpretation", Type: "string"}, {Name: "changes", Type: "string"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd midreq my-feature \"Add search bar\" --impact medium"},
	},
	{
		Command: "memory", Category: "lifecycle",
		Description: "Add or promote learning items",
		Usage:       "specd memory <slug> add|promote [flags]", Synopsis: "specd memory <slug> <add|promote> [flags]",
		LongDescription: "Manages persistent project learnings.",
		Flags:           []FlagMeta{{Name: "key", Type: "string"}, {Name: "pattern", Type: "string"}, {Name: "body", Type: "string"}, {Name: "source", Type: "string"}, {Name: "criticality", Type: "string"}, {Name: "related", Type: "string"}, {Name: "force", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd memory my-feature add --key db-lock --pattern \"parallel writes\" --body \"SQLite locks on concurrent write\" --source log --criticality important"},
	},
	{
		Command: "next", Category: "execution",
		Description: "Next runnable task",
		Usage:       "specd next <slug> [--all] [--json]", Synopsis: "specd next <slug> [--all] [--json]",
		LongDescription: "Finds and prints the next runnable task in the spec's task DAG.",
		Flags:           []FlagMeta{{Name: "all", Type: "boolean", Description: "Print all runnable tasks"}, {Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd next my-feature", "specd next my-feature --all --json"},
	},
	{
		Command: "dispatch", Category: "execution",
		Description: "Ready-to-run packets for frontier",
		Usage:       "specd dispatch <slug> [--json]", Synopsis: "specd dispatch <slug> [--json]",
		LongDescription: "Produces ready-to-run packets for all tasks in the current runnable frontier.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd dispatch my-feature --json"},
	},
	{
		Command: "verify", Category: "execution",
		Description:     "Run task verify command / record proof",
		Usage:           "specd verify <slug> <id>  |  specd verify <slug> --criterion <r>.<n> --status pass|fail --evidence \"...\"",
		Synopsis:        "specd verify <slug> [id] [flags]",
		LongDescription: "Runs a task's verification command and records the result, or records a per-criterion acceptance proof.",
		Flags:           []FlagMeta{{Name: "criterion", Type: "string"}, {Name: "status", Type: "string"}, {Name: "evidence", Type: "string"}, {Name: "revert-on-fail", Type: "boolean", Description: "On a failed verify, stash the working tree (recoverable) instead of leaving it dirty"}, {Name: "sandbox", Type: "string", Description: "Isolation backend for this run (none|bwrap|container); overrides verify.sandbox config"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Verification failed"}, {2, "Usage error"}, {3, "Spec or task not found"}},
		Examples:        []string{"specd verify my-feature T1", "specd verify my-feature --criterion 1.1 --status pass --evidence \"Tested manually\""},
	},
	{
		Command: "task", Category: "execution",
		Description:     "Evidence-gated status flip",
		Usage:           "specd task <slug> <id> --status <s> [--evidence \"...\"] [--reason \"...\"] [--force]",
		Synopsis:        "specd task <slug> <id> --status <status> [flags]",
		LongDescription: "Updates the status of a specific task. Completing requires a passing verify record.",
		Flags:           []FlagMeta{{Name: "status", Type: "string"}, {Name: "evidence", Type: "string"}, {Name: "reason", Type: "string"}, {Name: "force", Type: "boolean"}, {Name: "unverified", Type: "boolean"}, {Name: "tokens", Type: "string", Description: "Annotate task telemetry with a token count (stored, not computed)"}, {Name: "cost", Type: "string", Description: "Annotate task telemetry with a cost (stored, not computed)"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Gate verification failed"}, {2, "Usage error"}, {3, "Spec or task not found"}},
		Examples:        []string{"specd task my-feature T1 --status running", "specd task my-feature T1 --status complete --evidence \"Ran tests\"", "specd task my-feature T1 --status complete --evidence \"…\" --tokens 12000 --cost 0.42"},
	},
	{
		Command: "status", Category: "inspection",
		Description: "Render durable ledger / board",
		Usage:       "specd status [<slug>] [--json]", Synopsis: "specd status [<slug>] [--json]",
		LongDescription: "Renders the durable status board of a specific spec, or lists all specs.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd status", "specd status my-feature --json"},
	},
	{
		Command: "check", Category: "inspection",
		Description: "Run all validation gates",
		Usage:       "specd check <slug> [--json]", Synopsis: "specd check <slug> [--json]",
		LongDescription: "Runs all seven validation gates on the specified spec: ears, design, task-schema, dag, sync, traceability, and evidence.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Validation failed"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd check my-feature", "specd check my-feature --json"},
	},
	{
		Command: "context", Category: "inspection",
		Description: "Phase-scoped briefing",
		Usage:       "specd context <slug> [--json]", Synopsis: "specd context <slug> [--json]",
		LongDescription: "Provides a minimal phase-scoped briefing for the current spec phase.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd context my-feature", "specd context my-feature --json"},
	},
	{
		Command: "validate", Category: "inspection",
		Description:     "Check state.json against the open spec schema",
		Usage:           "specd validate <slug> --schema [--version <v>]",
		Synopsis:        "specd validate <slug> --schema [--version <v>]",
		LongDescription: "Validates a spec's on-disk state.json against the embedded open spec format JSON Schema. A structural/format conformance mode (shape, required keys, closed property sets, enums) — independent of the seven semantic gates in `specd check`. Read-only. Text by default; JSON under SPECD_JSON.",
		Flags:           []FlagMeta{{Name: "schema", Type: "boolean", Description: "Validate against the embedded JSON Schema (required)"}, {Name: "version", Type: "string", Description: "Schema version to validate against (default: current)"}, {Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Conformant"}, {1, "Conformance violations found"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd validate my-feature --schema", "SPECD_JSON=1 specd validate my-feature --schema"},
	},
	{
		Command: "schema", Category: "inspection",
		Description:     "Emit the embedded open spec format JSON Schema",
		Usage:           "specd schema [--version <v>]",
		Synopsis:        "specd schema [--version <v>]",
		LongDescription: "Writes the embedded, versioned JSON Schema for the specd on-disk artifacts to stdout. The schema is the published, machine-readable format contract; the Go types in internal/core are its single source of truth (a conformance test fails CI on drift). Requires no .specd/ root.",
		Flags:           []FlagMeta{{Name: "version", Type: "string", Description: "Schema version to emit (default: current)"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Unknown schema version"}, {2, "Usage error"}},
		Examples:        []string{"specd schema", "specd schema --version 1 > spec-schema.json"},
	},
	{
		Command: "report", Category: "inspection",
		Description: "Generate markdown or HTML report",
		Usage:       "specd report <slug> [--format md|html] [--out <path>] [--pr-summary]", Synopsis: "specd report <slug> [--format md|html] [--out <path>] [--pr-summary]",
		LongDescription: "Compiles a comprehensive HTML or Markdown progress report. With --pr-summary, emits a deterministic, network-free pull-request summary (Markdown, or JSON under SPECD_JSON): wave/task progress, gate status, and the commit↔task link map.",
		Flags:           []FlagMeta{{Name: "format", Type: "string"}, {Name: "out", Type: "string"}, {Name: "pr-summary", Type: "boolean", Description: "Emit a deterministic PR summary instead of the full report"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd report my-feature --format html --out ./report.html"},
	},
	{
		Command: "serve", Category: "inspection",
		Description: "Serve a read-only live dashboard",
		Usage:       "specd serve <slug> [--addr 127.0.0.1:8765]", Synopsis: "specd serve <slug> [--addr 127.0.0.1:8765]",
		LongDescription: "Starts a read-only HTTP server (loopback by default) that renders the same HTML as `specd report --format html` at GET /, and the JSON ReportData at GET /api/report. No mutating routes; data is rebuilt from disk per request.",
		Flags:           []FlagMeta{{Name: "addr", Type: "string", Description: "Bind address (default 127.0.0.1:8765)"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd serve my-feature", "specd serve my-feature --addr 127.0.0.1:9000"},
	},
	{
		Command: "replay", Category: "inspection",
		Description: "Replay a spec's audit timeline",
		Usage:       "specd replay <slug>", Synopsis: "specd replay <slug>",
		LongDescription: "Reconstructs a deterministic, read-only event timeline (task start/finish/verify/block + acceptance records) from the spec's on-disk audit data. Text by default; a typed JSON array under SPECD_JSON.",
		Flags:           []FlagMeta{},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd replay my-feature", "SPECD_JSON=1 specd replay my-feature"},
	},
	{
		Command: "diff", Category: "inspection",
		Description:     "Diff a spec's artifacts between two git refs",
		Usage:           "specd diff <slug> --from <ref> [--to <ref>]",
		Synopsis:        "specd diff <slug> --from <ref> [--to <ref>]",
		LongDescription: "Shows how a spec's on-disk artifacts changed between two git refs — a deterministic, read-only `git diff --name-status` scoped to the spec directory. --from is required; --to defaults to the working tree. Text by default; a typed JSON object under SPECD_JSON.",
		Flags:           []FlagMeta{{Name: "from", Type: "string", Description: "Base git ref (required)"}, {Name: "to", Type: "string", Description: "Target git ref (default: working tree)"}, {Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "git diff failed (bad ref / not a repo)"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd diff my-feature --from HEAD~5", "specd diff my-feature --from v0.1.0 --to HEAD"},
	},
	{
		Command: "watch", Category: "inspection",
		Description: "Stream runnable-frontier changes (NDJSON / SSE / webhook)",
		Usage:       "specd watch [--once] [--spec <slug>] [--sse <addr>] [--webhook <url>]", Synopsis: "specd watch [--once] [--spec <slug>] [--sse <addr>] [--webhook <url>]",
		LongDescription: "Watches spec state and emits a FrontierEvent whenever a spec's runnable task set changes. Read-only: it never writes state. Transports: by default NDJSON on stdout; --sse <addr> serves Server-Sent Events at GET /events over net/http; --webhook <url> POSTs each event on a non-blocking background worker with bounded retry/backoff. --once does a single pass and exits; long-running modes shut down cleanly on SIGINT/SIGTERM. Polls at SPECD_WATCH_INTERVAL_MS (default 1000ms). Stdlib-only.",
		Flags:           []FlagMeta{{Name: "once", Type: "boolean", Description: "Emit current frontiers once and exit"}, {Name: "spec", Type: "string", Description: "Limit the stream to a single spec slug"}, {Name: "sse", Type: "string", Description: "Serve Server-Sent Events at this bind address (e.g. 127.0.0.1:8766)"}, {Name: "webhook", Type: "string", Description: "POST each frontier event to this URL"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, ".specd/ not found"}},
		Examples:        []string{"specd watch --once", "specd watch --spec my-feature", "specd watch --sse 127.0.0.1:8766", "specd watch --webhook https://ci.example/hook"},
	},
	{
		Command: "waves", Category: "inspection",
		Description: "Show task wave DAG",
		Usage:       "specd waves <slug> [--json]", Synopsis: "specd waves <slug> [--json]",
		LongDescription: "Renders the task wave dependency graph in ASCII or JSON.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}, {3, "Spec not found"}},
		Examples:        []string{"specd waves my-feature"},
	},
	{
		Command:     "brain",
		Category:    "orchestration",
		Description: "Drive deterministic Brain orchestration sessions.",
		Usage:       "specd brain <start|status|step|pause|resume|cancel> ... [--program]",
		Synopsis:    "specd brain <start|status|step|pause|resume|cancel> ... [--program]",
		Flags: []FlagMeta{
			{Name: "program", Type: "boolean", Description: "operate on the cross-spec program session instead of one spec"},
			{Name: "session", Type: "string", Description: "explicit orchestration session id"},
			{Name: "approval-policy", Type: "string", Description: "required approval policy for start/step"},
			{Name: "max-workers", Type: "string", Description: "required worker concurrency limit for start/step"},
			{Name: "max-retries", Type: "string", Description: "required retry limit for start/step"},
			{Name: "timeout-seconds", Type: "string", Description: "required session timeout for start/step"},
			{Name: "cost-limit", Type: "string", Description: "optional host-reported cost limit"},
			{Name: "json", Type: "boolean", Description: "emit JSON"},
		},
		ExitCodes: []ExitCodeMeta{{0, "Success"}, {1, "Gate or validation failure"}, {2, "Usage error"}, {3, "Workspace or session not found"}},
		Examples:  []string{"specd brain start my-spec --approval-policy manual --max-workers 4 --max-retries 2 --timeout-seconds 7200 --json", "specd brain start --program --session 11111111111111111111111111111111 --approval-policy manual --max-workers 4 --max-retries 2 --timeout-seconds 7200 --json", "specd brain step my-spec --session 11111111111111111111111111111111 --approval-policy manual --max-workers 4 --max-retries 2 --timeout-seconds 7200"},
	},
	{
		Command:     "pinky",
		Category:    "orchestration",
		Description: "Record deterministic Pinky worker claims and reports.",
		Usage:       "specd pinky <claim|heartbeat|progress|report|block|release> ...",
		Synopsis:    "specd pinky <claim|heartbeat|progress|report|block|release> ...",
		Flags: []FlagMeta{
			{Name: "mission", Type: "string", Description: "mission JSON path or - for claim"},
			{Name: "session", Type: "string", Description: "session id"},
			{Name: "worker", Type: "string", Description: "worker id"},
			{Name: "spec", Type: "string", Description: "spec slug"},
			{Name: "task", Type: "string", Description: "task id"},
			{Name: "attempt", Type: "string", Description: "positive attempt number"},
			{Name: "percent", Type: "string", Description: "progress percent"},
			{Name: "message", Type: "string", Description: "progress message"},
			{Name: "reason", Type: "string", Description: "blocker reason"},
			{Name: "verification-ref", Type: "string", Description: "terminal verification reference"},
			{Name: "summary", Type: "string", Description: "terminal summary"},
			{Name: "changed-files", Type: "string", Description: "comma-separated changed files"},
			{Name: "git-head", Type: "string", Description: "git commit observed by the host worker"},
			{Name: "duration-ms", Type: "string", Description: "host-reported task duration in milliseconds"},
			{Name: "host-tokens", Type: "string", Description: "host-reported token count (stored, not computed)"},
			{Name: "host-cost", Type: "string", Description: "host-reported cost (stored, not computed)"},
			{Name: "json", Type: "boolean", Description: "emit JSON"},
		},
		ExitCodes: []ExitCodeMeta{{0, "Success"}, {1, "Gate or validation failure"}, {2, "Usage error"}, {3, "Workspace or session not found"}},
		Examples:  []string{"specd pinky claim --mission mission.json --json", "specd pinky progress --session s --worker w --spec my-spec --task T1 --attempt 1 --percent 50 --message working"},
	},
	{
		Command: "program", Category: "inspection",
		Description:     "Cross-spec DAG runnable frontier",
		Usage:           "specd program [status] [--json]  |  specd program <link|unlink> <spec> --on <dep>",
		Synopsis:        "specd program [status|link|unlink] [args] [flags]",
		LongDescription: "Manages cross-spec dependencies and displays the cross-spec runnable frontier.",
		Flags:           []FlagMeta{{Name: "on", Type: "string"}, {Name: "json", Type: "boolean"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error"}},
		Examples:        []string{"specd program status", "specd program link feat-b --on feat-a"},
	},
	{
		Command: "update", Category: "meta",
		Description: "Update specd to latest version",
		Usage:       "specd update [--force]", Synopsis: "specd update [--force]",
		LongDescription: "Downloads the latest pre-built binary from GitHub Releases and replaces the running binary.",
		Flags:           []FlagMeta{{Name: "force", Type: "boolean", Description: "Force update even if already up to date"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {1, "Update failed"}, {2, "Usage error"}},
		Examples:        []string{"specd update", "specd update --force"},
	},
	{
		Command: "uninstall", Category: "meta",
		Description:     "Remove specd from this machine",
		Usage:           "specd uninstall [--force] [--dry-run] [--json]",
		Synopsis:        "specd uninstall [--force] [--dry-run] [--json]",
		LongDescription: "Removes the specd install directory, the ~/.local/bin/specd link, and the '# specd' PATH lines install.sh added to your shell rc files (backed up to <rc>.specd.bak). A bare invocation only previews the plan; pass --force to actually remove. Project-local '.specd/' directories are always preserved.",
		Flags: []FlagMeta{
			{Name: "force", Type: "boolean", Description: "Perform the removal (without it, only the plan is shown)"},
			{Name: "dry-run", Type: "boolean", Description: "Show what would be removed and exit"},
			{Name: "json", Type: "boolean", Description: "Machine-readable output"},
		},
		ExitCodes: []ExitCodeMeta{{0, "Success"}, {1, "Uninstall failed"}, {2, "Usage error"}},
		Examples:  []string{"specd uninstall", "specd uninstall --dry-run", "specd uninstall --force"},
	},
	{
		Command: "version", Category: "meta",
		Description: "Show version information",
		Usage:       "specd version", Synopsis: "specd version",
		LongDescription: "Prints the version of the installed specd binary.",
		Flags:           []FlagMeta{}, ExitCodes: []ExitCodeMeta{{0, "Success"}},
		Examples: []string{"specd version"},
	},
	{
		Command: "mcp", Category: "meta",
		Description:     "Run the MCP stdio server (or print a host config snippet)",
		Usage:           "specd mcp [--root <path>] [--config <host>]",
		Synopsis:        "specd mcp [--root <path>] [--config <host>]",
		LongDescription: "Starts a Model Context Protocol (MCP) JSON-RPC 2.0 server over stdio, exposing every read-safe and state-mutating specd command as an MCP tool. A thin transport over the existing handlers — stdlib-only, no network, no LLM calls.\n\n--config <host> prints a ready-to-paste config snippet for the named MCP host and exits without starting the server. Supported hosts: antigravity, claude-code, claude-desktop, codex, cursor, gemini, vscode. Combine with --root to substitute your project path into the snippet.",
		Flags: []FlagMeta{
			{Name: "root", Type: "string", Description: "Resolve specs against this project root (also substituted into --config output)"},
			{Name: "config", Type: "string", Description: "Print ready-to-paste MCP config for a host (antigravity | claude-code | claude-desktop | codex | cursor | gemini | vscode) and exit"},
		},
		ExitCodes: []ExitCodeMeta{{0, "Success (stream closed or config printed)"}, {1, "Server error"}, {2, "Usage error"}},
		Examples:  []string{"specd mcp", "specd mcp --root /path/to/project", "specd mcp --config cursor", "specd mcp --config codex --root /path/to/project"},
	},
	{
		Command: "help", Category: "meta",
		Description: "Show detailed help for a command",
		Usage:       "specd help [command]", Synopsis: "specd help [command]",
		LongDescription: "Prints summary documentation for all commands, or detailed reference for a single command.",
		Flags:           []FlagMeta{{Name: "json", Type: "boolean", Description: "Output the entire command registry as JSON"}},
		ExitCodes:       []ExitCodeMeta{{0, "Success"}, {2, "Usage error (unknown command)"}},
		Examples:        []string{"specd help", "specd help init", "specd help --json"},
	},
}
