package core

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestManagedRegionsCarryEditingNotice pins R4.1: every steering managed region
// states inside itself that it is regenerated and that edits belong below the
// closing marker — and the notice survives `init --repair`, since it lives in
// the regenerated template, not below the marker.
func TestManagedRegionsCarryEditingNotice(t *testing.T) {
	assets, err := ManagedAssets()
	if err != nil {
		t.Fatal(err)
	}
	steering := 0
	for _, a := range assets {
		if !strings.HasPrefix(a.Name, "steering/") || a.Name == "steering/memory.md" {
			continue
		}
		steering++
		block := a.Block()
		if !strings.Contains(block, "Regenerated by") || !strings.Contains(block, "below the closing marker") {
			t.Fatalf("%s managed region lacks the editing notice:\n%s", a.Name, block)
		}
	}
	if steering == 0 {
		t.Fatal("no steering managed assets found")
	}

	// Survives repair: scaffold, repair, and confirm the notice is still present.
	root := t.TempDir()
	if err := WriteScaffold(root); err != nil {
		t.Fatal(err)
	}
	if _, err := ApplyManagedRepair(root); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(root, ".specd", "steering", "tech.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "below the closing marker") {
		t.Fatalf("editing notice lost after init --repair:\n%s", raw)
	}
}
